AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    TeamName:
        Type: String
        Default: ATOM
    ProjectName:
        Type: String
        Default: HistoryWebTool    
    ENV:
        Description: Specify for differnt environments in the same account
        Type: String
        Default: dev
    
Mappings:
    SecurityGroupMap:
        dev:
          value: sg-0baebab4732033b56
        qa:
          value: sg-0baebab4732033b56
        cert:
          value: sg-073570b817287fac4
        prod:
          value: sg-073570b817287fac4
    VPCMap:
      dev:
        value: vpc-07ae063405f3dad33
      qa:
        value: vpc-07ae063405f3dad33
      cert:
        value: vpc-055df18b21b070966
      prod:
        value: vpc-055df18b21b070966
    SubnetMap:
        dev:
          value: subnet-03dafe4a903bf77f3,subnet-09d9e4fc315254db0
        qa:
          value: subnet-03dafe4a903bf77f3,subnet-09d9e4fc315254db0
        cert:
          value: subnet-0b0a66b5da5157ed9,subnet-056a9da3e0fb617bc
        prod:
          value: subnet-0b0a66b5da5157ed9,subnet-056a9da3e0fb617bc
    ACMCertificateARN:
        dev: 
          value: arn:aws:acm:ap-southeast-1:476985428237:certificate/d922e15c-9c5d-427e-a97c-9185370f94dc
        qa: 
          value: arn:aws:acm:ap-southeast-1:476985428237:certificate/d922e15c-9c5d-427e-a97c-9185370f94dc
        cert:
          value: arn:aws:acm:us-east-1:206710830665:certificate/8d0cb4af-7ce0-4979-88f5-6487c3a15702
        prod:
          value: arn:aws:acm:us-east-1:206710830665:certificate/8d0cb4af-7ce0-4979-88f5-6487c3a15702
Resources:    
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${TeamName}-${ProjectName}-${ENV}'
      Scheme: internal
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '180'
      Subnets: !Split
      - ","
      - !FindInMap
        - SubnetMap
        - !Ref ENV
        - value
      SecurityGroups: !Split
      - ","
      - !FindInMap
        - SecurityGroupMap
        - !Ref ENV
        - value
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref 'LoadBalancer'
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref 'TargetGroupUI'      
      Port: '443'
      Protocol: HTTPS
      Certificates:
      - CertificateArn: !FindInMap
        - ACMCertificateARN
        - !Ref ENV
        - value
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2019-08
  ListenerRuleUI:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'Listener'
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'TargetGroupUI'
      Conditions:
      - Field: path-pattern
        Values: [/]      
      Priority: 1
  TargetGroupUI:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${TeamName}-${ProjectName}-UI-${ENV}'
      HealthCheckIntervalSeconds: 180
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 120
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !FindInMap
      - VPCMap
      - !Ref ENV
      - value

  ListenerRuleAPI:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'Listener'
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'TargetGroupAPI'
      Conditions:
      - Field: path-pattern
        Values: [/api/*]      
      Priority: 2
  TargetGroupAPI:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${TeamName}-${ProjectName}-API-${ENV}'
      HealthCheckIntervalSeconds: 180
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 120
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !FindInMap
      - VPCMap
      - !Ref ENV
      - value
  ListenerRuleMNCR:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'Listener'
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'TargetGroupMNCR'
      Conditions:
      - Field: path-pattern
        Values: [/mncr/*]      
      Priority: 3
  TargetGroupMNCR:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${TeamName}-${ProjectName}-MNCR-${ENV}'
      HealthCheckIntervalSeconds: 180
      HealthCheckPath: /mncr/index
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 120
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !FindInMap
      - VPCMap
      - !Ref ENV
      - value
Outputs:
  TargetGroupUI:
    Description: TargetGroupUI
    Value: !Ref 'TargetGroupUI'
    Export:
      Name : !Sub '${TeamName}-${ProjectName}-UI-${ENV}'
  TargetGroupAPI:
    Description: TargetGroupAPI
    Value: !Ref 'TargetGroupAPI'
    Export:
      Name : !Sub '${TeamName}-${ProjectName}-API-${ENV}'
  TargetGroupMNCR:
    Description: TargetGroupMNCR
    Value: !Ref 'TargetGroupMNCR'
    Export:
      Name : !Sub '${TeamName}-${ProjectName}-MNCR-${ENV}'
